name = "GeometricAlgebra"
uuid = "11bbe1ca-eae6-48c2-942c-9f17e43de0f0"
authors = ["jollywatt <jo.alex.w@gmail.com>"]
version = "0.2.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
PrettyTables = "^2"
