[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
GeometricAlgebra = "11bbe1ca-eae6-48c2-942c-9f17e43de0f0"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Documenter = "1"
DocumenterCitations = "1.2"
